post_install() {
    # Config time zone
    ln -sf /usr/share/zoneinfo/America/Sao_Paulo "/etc/localtime"
    hwclock --systohc

    # Config localization
    sed 's/#pt_BR.UTF-8/pt_BR.UTF-8/' -i /etc/locale.gen
    sed 's/#en_US.UTF-8/en_US.UTF-8/' -i /etc/locale.gen
    locale-gen

    # Enable services
    timedatectl set-ntp true
    systemctl enable NetworkManager.service
    systemctl enable docker.service
}
